apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  MYSQL_ROOT_PASSWORD: root_password
  MYSQL_DATABASE: wordpress_db
  MYSQL_USER: wp_user
  MYSQL_PASSWORD: wp_password
  WORDPRESS_DB_HOST: mysql-service
  WORDPRESS_DB_NAME: wordpress_db
  WORDPRESS_DB_USER: wp_user
  WORDPRESS_DB_PASSWORD: wp_password
